### ISSUE TITLE
problems with 01-entering-data.Rmd

### ISSUE THREAD

**Issue by ahurford** [ahurford/quantitative-training-resources#7]
Hi @JoanyMarino,

The ```{r} code sections in 01-entering-data.Rmd were causing my bookdown compilitation to fail, i.e., when I click "Build Book" with the .Rproj open. I comment this out for now. Can you take a look and see if you can fix it up. Maybe not this morning (Thursday) as Yolanda and I are planning to work on this now.

Amy

**Comment by JoanyMarino** [comment]
Hi Amy,

Sounds good. I'll check on that tomorrow.

Thanks for letting me know.
